//! Implements various bounders for bounding the size of models, generated by the chase.
//!
//! The bounders are instances of [`Bounder`].
//!
//! [`Bounder`]: crate::chase::Bounder
use crate::chase::{Bounder, Model, Observation};

/// Bounds the size of a [model] by the number of elements in its [domain].
///
/// [model]: crate::chase::Model
/// [domain]: crate::chase::Model::domain()
pub struct DomainSize {
    /// Is the maximum size of the [domain] of elements for models accepted by this bounder.
    ///
    /// [domain]: crate::chase::Model::domain()
    max_domain_size: usize,
}

impl From<usize> for DomainSize {
    fn from(size: usize) -> Self {
        Self {
            max_domain_size: size,
        }
    }
}

impl Bounder for DomainSize {
    fn bound<M: Model>(&self, model: &M, observation: &Observation<M::TermType>) -> bool {
        match observation {
            Observation::Fact { relation: _, terms } => {
                let model_size = model.domain().len();
                let size = terms
                    .iter()
                    .map(|t| model.element(t))
                    .filter(|t| t.is_none())
                    .count();
                model_size + size > self.max_domain_size
            }
            Observation::Identity { left, right } => {
                let mut size = model.domain().len();
                if model.element(left).is_none() {
                    size += 1;
                }
                if model.element(right).is_none() {
                    size += 1;
                }
                size > self.max_domain_size
            }
        }
    }
}
